#pragma once

#define LEFT_NUM_ROW   KC_1 , KC_2, KC_3, KC_4, KC_5
#define RIGHT_NUM_ROW  KC_6 , KC_7, KC_8, KC_9, KC_0

#define LEFT_QW_ROW_1  KC_Q , KC_W , KC_E , KC_R , KC_T
#define LEFT_QW_ROW_2  GUI_T(KC_A) , ALT_T(KC_S) , CTL_T(KC_D) , SFT_T(KC_F) , LT(_RS, KC_G)
#define LEFT_QW_ROW_3  KC_Z , KC_X , KC_C , KC_V , KC_B

#define RIGHT_QW_ROW_1 KC_Y , KC_U , KC_I , KC_O , KC_P
#define RIGHT_QW_ROW_2 LT(_RS, KC_H) , SFT_T(KC_J) , CTL_T(KC_K) , ALT_T(KC_L) , GUI_T(KC_SCLN)
#define RIGHT_QW_ROW_3 KC_N , KC_M , KC_COMM , KC_DOT , KC_SLSH

#define LEFT_FUNC_ROW  KC_F1, KC_F2, KC_F3, KC_F4, KC_F5
#define RIGHT_FUNC_ROW KC_F6, KC_F7, KC_F8, KC_F9, KC_F10

#define LEFT_SYMBOL_ROW_1 S(KC_1) , S(KC_2) , S(KC_3) , S(KC_4)  , S(KC_5)
#define LEFT_SYMBOL_ROW_2 S(KC_9) , KC_LEFT , KC_UP   , KC_RIGHT , S(KC_0)
#define LEFT_SYMBOL_ROW_3 KC_LBRC, KC_RBRC, KC_DOWN, S(KC_LBRC), S(KC_RBRC)

#define RIGHT_NUMPAD_ROW_1 S(KC_6) , KC_7 , KC_8 , KC_9 , KC_0
#define RIGHT_NUMPAD_ROW_2 S(KC_7), KC_4, KC_5, KC_6, KC_MINS
#define RIGHT_NUMPAD_ROW_3 S(KC_8), KC_1, KC_2, KC_3, KC_0

#define LEFT_MOUSE_ROW_1 KC_VOLU , KC_MS_BTN1 , KC_MS_BTN3 , KC_MS_BTN2  , KC_PGUP
#define LEFT_MOUSE_ROW_2 KC_VOLD , KC_MS_LEFT , KC_MS_UP   , KC_MS_RIGHT , KC_PGDN
#define LEFT_MOUSE_ROW_3 KC_MUTE , KC_MPLY    , KC_MS_DOWN , KC_MPRV     , KC_MNXT
#define RIGHT_FUNCPAD_ROW_1 KC_HOME , KC_F7 , KC_F8 , KC_F9 , KC_F10
#define RIGHT_FUNCPAD_ROW_2 KC_END  , KC_F4 , KC_F5 , KC_F6 , KC_F11
#define RIGHT_FUNCPAD_ROW_3 KC_PSCR , KC_F1  , KC_F2 , KC_F3 , KC_F12

#define LEFT_PRIMARY_THUMB_CLUSTER OSM(MOD_LSFT) , LT(_LW, KC_BSPC) , KC_ESC
#define RIGHT_PRIMARY_THUMB_CLUSTER KC_TAB , LT(_LW, KC_SPC) , KC_ENT

#define LEFT_TRANSPARENT_THUMB_CLUSTER(LAYER) _______, _______, TO(LAYER)
#define RIGHT_TRANSPARENT_THUMB_CLUSTER _______, _______, _______

#define LAYOUT_wrapper(...) LAYOUT(__VA_ARGS__)
